### ISSUE TITLE
CLIPLoaderDisTorch2MultiGPU Allocation on device error

### ISSUE THREAD

**Issue by sinand99** [pollockjj/ComfyUI-MultiGPU#104]
I am using Qwen Image in ComfyUI and having a hard time because its text encoder is larger than others models like Flux. It is 9 GB which does not fit into my  8 GB card and don't wanna use low quality GGUFs. So I saw your Multi GPU node and thought this is perfect for me. But it gives me OOM error just like the regular Clip Loader node. It does not offload to CPU at all no matter which setting I change. Every time I click Run button, it shows me Allocation on device pop up. I tried expert mode allocations, but your node ignores it and want to load  the WHOLE model in to VRAM. So am I using it wrong or is it a bug? 

What I want is this:

- Load 7 GB of the text encoder partially onto VRAM
- Offload the remaining 2GB onto system RAM
- Run the text encoder and unload both VRAM and RAM when it is done parsing the prompt.
- Continue the workflow

This is how I run LLM models with llama.cpp and it works perfect. How can I do the same with Multi GPU? 

Encoder: https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/blob/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors
GPU: 3070 Ti 8GB
RAM: 64GB
ComfyUI: 0.3.5.7
Torch: 2.8.0+cu128
Python: 3.13.7
SageAttention: 2.2

<img width="493" height="596" alt="Image" src="https://github.com/user-attachments/assets/3e65760c-46f6-4b73-b4da-33517ddfd6a9" />

Things I tried:

- Normally I use Nvidia CUDA No system fallback option in the control panel, I tested by changing it but still getting the error.
- Used with and without ComyUI --disable-smart-memory flag. No change, still getting the error.

**Comment by TingTingin** [comment]
This is a bit funny but i had the reverse of this with my 3070 8gb gpu where i could load the qwen clip fine with the comfy native clip loader node but it stopped working with a recent update to the multigpu repo so in order to load qwen i had to uninstall this node as it affects the native comfy node 

You want prefer sysmem fallback and to try using the native comfy clip loader and it should work (i know you said you tried this but i have the same setup and it is working with these settings) if its still not working try a pc restart

basically on the latest version of this node it seems that clip loading is bugged 

but native comfyui should work I have essentially the same setup as you and native clip loader works with comfy

3070 8gb
64 gb RAM 
Torch: 2.7
SageAttention

**Comment by sinand99** [comment]
@TingTingin yes we have the same problem. When I enable the sysmem fallback, comfy clip loader works but it gets horribly slow as the VRAM spills over the shared GPU Memory. And sometimes Qwen Edit cannot detect the input images properly, so I disable it and use Q5 GGUF instead. But lower quants are not good, so I prefer fp8.

I guess MultiGPU handles the clips differently than the normal models, but what I am surprised is DisTorch2 node completely ignores the cpu offload setting and tries to use VRAM which is the opposite of what it is supposed to do. This is definitely a bug, probably related to Qwen, because I didn't see anyone complaining about T5 encoder.

**Comment by TingTingin** [comment]
Do you mean the generation gets slower? if so that shouldn't happen as the clip encoder is only called once at the start to encode the prompt so the speed should always be the same if you mean the actual encoding of the prompt it only takes a few secs on my machine

`
 "Qwen Edit cannot detect the input images properly" `

this is interesting haven't noticed any issues with qwen edit not detecting the images properly i do use the Q6 GGUF for qwen edit though

**Comment by sinand99** [comment]
The clip encoder is not called once, it is called every time you change the prompt. It is fast at first, but next generations slows down  when I keep changing the prompt. For example, the second gen takes 200 seconds on my system (when cuda fallback is enabled).

I use Q4 GGUF + Q8 mmproj file. That may be the reason for poor detection. I ask Qwen Edit to remove the text from the image but it fails to do that.

**Comment by TingTingin** [comment]
Your misunderstanding i meant it's called once per generation therefore it shouldn't affect the generation speed I know it has to encode every unique prompt since comfy caches the results I was asking since my individual encoding speed is fast

`
if you mean the actual encoding of the prompt it only takes a few secs on my machine
`

There shouldn't be a per encoding speed issue but it seems with your PC there is some other issue slowing down the speed of an individual encode

Also this

` I ask Qwen Edit to remove the text from the image but it fails to do that.`

can happen with any of these edit models sometimes you wont see a change in the image this can occasionally happen with the full size encoder and model as well it depends on image seed sampler etc if your still having that issue you can try a different seed or sampler er_sde tends to lead to more change for example

**Comment by clover-supply** [comment]
The legacy node still works, iterestingly. I'll try the gguf version after I download the clip.

edit: new GGUF distorch2 clip loader works so it's only the standard that's bad

**Comment by pollockjj** [comment]
Hey guys, looks like this is an issue affecting several of you. Let me dive in. Any load logs or workflows that clearly show/illustrate the issue is greatly appreciated.

I will make this my number one priority, but the more info provided, the more I can be sure the fix I come up with works for all of you.

**Comment by clover-supply** [comment]
> Hey guys, looks like this is an issue affecting several of you. Let me dive in. Any load logs or workflows that clearly show/illustrate the issue is greatly appreciated.
> 
> I will make this my number one priority, but the more info provided, the more I can be sure the fix I come up with works for all of you.

Setting device to cpu or offloading a ton of ram doesn't seem to do anything.

# ComfyUI Error Report
## Error Details
- **Node ID:** 349
- **Node Type:** CLIPLoaderDisTorch2MultiGPU
- **Exception Type:** torch.OutOfMemoryError
- **Exception Message:** Allocation on device 
This error means you ran out of memory on your GPU.

TIPS: If the workflow worked before you might have accidentally set the batch_size to a large number.
## Stack Trace
```
  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui-multigpu\distorch_2.py", line 615, in override
    out = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\nodes.py", line 948, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\sd.py", line 782, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\sd.py", line 988, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\sd.py", line 110, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\pixart_t5.py", line 41, in __init__
    super().__init__(device=device, dtype=dtype, model_options=model_options)

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\pixart_t5.py", line 22, in __init__
    super().__init__(device=device, dtype=dtype, name="t5xxl", clip_model=T5XXLModel, model_options=model_options)

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 675, in __init__
    setattr(self, self.clip, clip_model(device=device, dtype=dtype, model_options=model_options, **kwargs))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\pixart_t5.py", line 12, in __init__
    super().__init__(**kwargs)

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\sd3_clip.py", line 19, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config=textmodel_json_config, dtype=dtype, special_tokens={"end": 1, "pad": 0}, model_class=comfy.text_encoders.t5.T5, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 121, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\t5.py", line 232, in __init__
    self.encoder = T5Stack(self.num_layers, model_dim, inner_dim, config_dict["d_ff"], config_dict["dense_act_fn"], config_dict["is_gated_act"], config_dict["num_heads"], config_dict["model_type"] != "umt5", dtype, device, operations)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\t5.py", line 197, in __init__
    [T5Block(model_dim, inner_dim, ff_dim, ff_activation, gated_act, num_heads, relative_attention_bias=((not relative_attention) or (i == 0)), dtype=dtype, device=device, operations=operations) for i in range(num_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\t5.py", line 185, in __init__
    self.layer.append(T5LayerFF(model_dim, ff_dim, ff_activation, gated_act, dtype, device, operations))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\t5.py", line 57, in __init__
    self.DenseReluDense = T5DenseGatedActDense(model_dim, ff_dim, ff_activation, dtype, device, operations)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\ComfyUI\comfy\text_encoders\t5.py", line 39, in __init__
    self.wi_0 = operations.Linear(model_dim, ff_dim, bias=False, dtype=dtype, device=device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Gaming\Documents\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)

```
## System Information
- **ComfyUI Version:** 0.3.56
- **Arguments:** ComfyUI\main.py --windows-standalone-build --use-sage-attention --fast fp16_accumulation
- **OS:** nt
- **Python Version:** 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.8.0+cu128
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12877955072
  - **VRAM Free:** 11587813376
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

**Comment by pollockjj** [comment]
Hey all, I fixed a few bugs - my standard MultiGPU CLIP device assignation didn't carry over to distorch2; that was an oversight on my part, along with some memory clean-up that might help some people with "dangling chads" on iterative usages of the loader.

Please give it a shot and let me know if the behavior is improved.

**Comment by sinand99** [comment]
@pollockjj I still get OOM in 0.33 seconds when I click RUN button. 

<img width="1281" height="477" alt="Image" src="https://github.com/user-attachments/assets/271056e4-9ee3-4e3a-9372-639ec3554065" />

**Comment by sinand99** [comment]
The same error on CLIPLoaderMultiGPU. It runs fine for first time, then on the second run, it tries to use GPU, even though CPU device is selected.

 
<img width="1409" height="555" alt="Image" src="https://github.com/user-attachments/assets/0727ac27-6820-4a73-8dda-0767f1b6dd4b" />


```
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "G:\AI\Image\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\AI\Image\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "G:\AI\Image\ComfyUI\nodes.py", line 74, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 170, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 231, in encode_from_tokens
    self.load_model()
    ~~~~~~~~~~~~~~~^^
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 264, in load_model
    model_management.load_model_gpu(self.patcher)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 688, in load_model_gpu
    return load_models_gpu([model])
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 683, in load_models_gpu
    loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 494, in model_load
    self.model_use_more_vram(use_more_vram, force_patch_weights=force_patch_weights)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 523, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory, force_patch_weights=force_patch_weights)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\custom_nodes\comfyui-multigpu\distorch_2.py", line 72, in new_partially_load
    result = original_partially_load(self, device_to, extra_memory, force_patch_weights)
  File "G:\AI\Image\ComfyUI\comfy\model_patcher.py", line 856, in partially_load
    self.patch_model(load_weights=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\custom_nodes\comfyui-kjnodes\nodes\model_optimization_nodes.py", line 509, in patched_patch_model
    self.load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights, full_load=full_load)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_patcher.py", line 706, in load
    x[2].to(device_to)
    ~~~~~~~^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1369, in to
    return self._apply(convert)
           ~~~~~~~~~~~^^^^^^^^^
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 955, in _apply
    param_applied = fn(param)
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1355, in convert
    return t.to(
           ~~~~^
        device,
        ^^^^^^^
        dtype if t.is_floating_point() or t.is_complex() else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        non_blocking,
        ^^^^^^^^^^^^^
    )
    ^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 3.80 seconds
```

**Comment by clover-supply** [comment]
Only managed to make it run in cpu only mode after update.

**Comment by sinand99** [comment]
Checked again after the latest updates. Still getting OOM with Qwen Image Edit using ClipLoaderGGUFDistorch2MultiGPU

```
[MultiGPU Initialization] current_text_encoder_device and current_text_encoder_initial_device set to: cuda:0
gguf qtypes: Q8_0 (198), F32 (141)
Dequantizing token_embd.weight to prevent runtime OOM.
Attenpting to find mmproj file for text encoder...
Using mmproj 'Qwen2.5-VL-7B-Instruct_mmproj-Q8.gguf' for text encoder 'Qwen2.5-VL-7B-Instruct-Q8_0.gguf'.
gguf qtypes: F32 (291), Q8_0 (194), F16 (34)
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
[MultiGPU_DisTorch2] Settings changed for model 5bb00887. Previous settings hash: 61f7de48a8014237da12a57c6a17b35417f35720b4c05727ba80c0efe2158ec2, New settings hash: 93671afe4a44fd89284e444a1a2420396b6499e712106fdbeea3aff26d27ab5f. Forcing reload.
gguf qtypes: Q8_0 (198), F32 (141)
Dequantizing token_embd.weight to prevent runtime OOM.
Attenpting to find mmproj file for text encoder...
Using mmproj 'Qwen2.5-VL-7B-Instruct_mmproj-Q8.gguf' for text encoder 'Qwen2.5-VL-7B-Instruct-Q8_0.gguf'.
gguf qtypes: F32 (291), Q8_0 (194), F16 (34)
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
[MultiGPU_DisTorch2] Full allocation string: #cuda:0;3.6;cpu
Requested to load WanVAE
0 models unloaded.
loaded completely 0.0 242.02829551696777 True
Requested to load QwenImageTEModel_
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "G:\AI\Image\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\AI\Image\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "G:\AI\Image\ComfyUI\comfy_extras\nodes_qwen.py", line 40, in encode
    conditioning = clip.encode_from_tokens_scheduled(tokens)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 172, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 233, in encode_from_tokens
    self.load_model()
    ~~~~~~~~~~~~~~~^^
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 266, in load_model
    model_management.load_model_gpu(self.patcher)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 688, in load_model_gpu
    return load_models_gpu([model])
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 683, in load_models_gpu
    loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 494, in model_load
    self.model_use_more_vram(use_more_vram, force_patch_weights=force_patch_weights)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_management.py", line 523, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory, force_patch_weights=force_patch_weights)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\custom_nodes\comfyui-multigpu\distorch_2.py", line 85, in new_partially_load
    self.patch_model(load_weights=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\custom_nodes\comfyui-kjnodes\nodes\model_optimization_nodes.py", line 510, in patched_patch_model
    self.load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights, full_load=full_load)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 82, in load
    super().load(*args, force_patch_weights=True, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\model_patcher.py", line 706, in load
    x[2].to(device_to)
    ~~~~~~~^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1369, in to
    return self._apply(convert)
           ~~~~~~~~~~~^^^^^^^^^
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 955, in _apply
    param_applied = fn(param)
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1355, in convert
    return t.to(
           ~~~~^
        device,
        ^^^^^^^
        dtype if t.is_floating_point() or t.is_complex() else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        non_blocking,
        ^^^^^^^^^^^^^
    )
    ^
  File "G:\AI\Image\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 58, in to
    new = super().to(*args, **kwargs)
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\_tensor.py", line 1669, in __torch_function__
    ret = func(*args, **kwargs)
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
```

**Comment by sinand99** [comment]
safetensors clip loader crashes as well. See logs below.

```
[MultiGPU Initialization] current_text_encoder_device and current_text_encoder_initial_device set to: cuda:0
Using scaled fp8: fp8 matrix mult: False, scale input: False
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "G:\AI\Image\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\AI\Image\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "G:\AI\Image\ComfyUI\custom_nodes\comfyui-multigpu\distorch_2.py", line 729, in override
    temp_out = fn(*args, **kwargs)
  File "G:\AI\Image\ComfyUI\nodes.py", line 948, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 834, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 1051, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 112, in __init__
    self.cond_stage_model = clip(**(params))
                            ~~~~^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 84, in __init__
    super().__init__(device=device, dtype=dtype, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 48, in __init__
    super().__init__(device=device, dtype=dtype, name="qwen25_7b", clip_model=Qwen25_7BVLIModel, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\sd1_clip.py", line 675, in __init__
    setattr(self, self.clip, clip_model(device=device, dtype=dtype, model_options=model_options, **kwargs))
                             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 43, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config={}, dtype=dtype, special_tokens={"pad": 151643}, layer_norm_hidden_state=False, model_class=comfy.text_encoders.llama.Qwen25_7BVLI, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\sd1_clip.py", line 121, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\llama.py", line 392, in __init__
    self.visual = qwen_vl.Qwen2VLVisionTransformer(hidden_size=1280, output_hidden_size=config.hidden_size, device=device, dtype=dtype, ops=operations)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 300, in __init__
    VisionBlock(hidden_size, intermediate_size, num_heads, device, dtype, ops)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 241, in __init__
    self.mlp = VisionMLP(hidden_size, intermediate_size, device=device, dtype=dtype, ops=ops)
               ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 228, in __init__
    self.down_proj = ops.Linear(intermediate_size, hidden_size, bias=True, device=device, dtype=dtype)
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\ops.py", line 385, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
```

**Comment by pollockjj** [comment]
@sinand99  - if you could attach a workflow I will attempt to run it on the various evaluation machines I have here and see if I can replicate your issue.

I concur this should not be happening with your current configuration and I would like to understand why.

I have some reports from users that this is happening with QWEN but not other models but I would like to replicate your exact situation and see if I can reproduce the problem.

Also, do you work with any other workflows with models where a large clip is (or could be if you moved to a fp16 version) is being loaded and we see/don't see the issue?

I am on discord as @italbar if you wish to ping me there.

**Comment by sinand99** [comment]
Here is the workflow:
[qwen_image_edit_multigpu.json](https://github.com/user-attachments/files/22315175/qwen_image_edit_multigpu.json)

I do not have issues with other models because they use standard T5 fp8 models which is around 4GB. Qwen text encoder is 8GB, so I cannot use it with regular comfy clip loader. I saw you claimed your node can offload safetensors to cpu, so I wanted to try it. I tried and both fp8 safetensors and Q8 GGUF, both fail and complains that I am out of GPU memory.

<img width="1588" height="1067" alt="Image" src="https://github.com/user-attachments/assets/f0481182-e8d6-479b-ac67-50eb1dd42448" />

Note: I see in the logs the error happens during Vision Layer loading. Maybe the reason is Qwen2.5-VL-7B-Instruct is not a standard text encoder, it is an LLM model with a vision layer which can conflict with the loader and needs special memory management?

Logs:

```
[MultiGPU Initialization] current_text_encoder_device and current_text_encoder_initial_device set to: cuda:0
Using scaled fp8: fp8 matrix mult: False, scale input: False
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "G:\AI\Image\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\AI\Image\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "G:\AI\Image\ComfyUI\custom_nodes\comfyui-multigpu\distorch_2.py", line 729, in override
    temp_out = fn(*args, **kwargs)
  File "G:\AI\Image\ComfyUI\nodes.py", line 948, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 834, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 1051, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 112, in __init__
    self.cond_stage_model = clip(**(params))
                            ~~~~^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 84, in __init__
    super().__init__(device=device, dtype=dtype, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 48, in __init__
    super().__init__(device=device, dtype=dtype, name="qwen25_7b", clip_model=Qwen25_7BVLIModel, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\sd1_clip.py", line 675, in __init__
    setattr(self, self.clip, clip_model(device=device, dtype=dtype, model_options=model_options, **kwargs))
                             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 43, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config={}, dtype=dtype, special_tokens={"pad": 151643}, layer_norm_hidden_state=False, model_class=comfy.text_encoders.llama.Qwen25_7BVLI, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\sd1_clip.py", line 121, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\llama.py", line 392, in __init__
    self.visual = qwen_vl.Qwen2VLVisionTransformer(hidden_size=1280, output_hidden_size=config.hidden_size, device=device, dtype=dtype, ops=operations)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 300, in __init__
    VisionBlock(hidden_size, intermediate_size, num_heads, device, dtype, ops)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 241, in __init__
    self.mlp = VisionMLP(hidden_size, intermediate_size, device=device, dtype=dtype, ops=ops)
               ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 228, in __init__
    self.down_proj = ops.Linear(intermediate_size, hidden_size, bias=True, device=device, dtype=dtype)
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\ops.py", line 385, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 0.39 seconds
 
```

**Comment by pollockjj** [comment]
@sinand99,

A couple of things:

1. I have loaded and ran your workflow with modifications. You have KJ nodes in there and another node pack that looks like you were attempting to do additional model management and patching. I removed those and disabled the KJ nodes as part of my troubleshooting. 

2. I was able to run the modified workflow successfully. What you see linked here is a full log file - it shows what was run and the MultiGPU logging from `get prompt` until the end. The fact that you are not even getting to the allocation section suggests other causes. Without a Crystools or System level grab of memory usage before, during, and after the OOM I cannot tell what is going on definitively.

3. [Here is the modified workflow](https://gist.github.com/pollockjj/419e3e07182765394a91f682cab40d07) that eliminates other nodes as potential interactions and runs correctly when ran on my system on the latest update of ComfyUI-MultiGPU. Please check your results with it, and post the resultant log from `get prompt` if possible so we can fully trace execution.

```
got prompt
Requested to load QwenImageTEModel_
[MultiGPU_DisTorch2] Using CLIP-specific allocation for model 9b313bd7 (HEAD PRESERVATION ENABLED)
[MultiGPU_DisTorch2_CLIP] CLIP Compute Device: cuda:0
[MultiGPU_DisTorch2_CLIP] Expert String Examples:
  Direct(byte) Mode - cuda:0,500mb;cuda:1,3.0g;cpu,5gb* -> '*' cpu = over/underflow device, put 0.50gb on cuda0, 3.00gb on cuda1, and 5.00gb (or the rest) on cpu
  Ratio(%) Mode - cuda:0,8%;cuda:1,8%;cpu,4% -> 8:8:4 ratio, put 40% on cuda0, 40% on cuda1, and 20% on cpu
===============================================
    DisTorch2 Model Virtual VRAM Analysis
===============================================
Object   Role   Original(GB) Total(GB)  Virt(GB)
-----------------------------------------------
cuda:0   recip      23.55GB   26.55GB   +3.00GB
cpu      donor     124.97GB  121.97GB   -3.00GB
-----------------------------------------------
model    model       7.72GB    4.72GB   -3.00GB
[MultiGPU_DisTorch2_CLIP] Final CLIP Allocation String: cuda:0,0.2006;cpu,0.0240;cuda:1,0.0;cuda:2,0.0
==================================================
    DisTorch2 CLIP Model Device Allocations
==================================================
Device    VRAM GB    Dev %   Model GB    Dist %
--------------------------------------------------
cuda:0      23.55    20.1%       4.72     61.2%
cuda:1      23.56     0.0%       0.00      0.0%
cuda:2       5.61     0.0%       0.00      0.0%
cpu        124.97     2.4%       3.00     38.8%
--------------------------------------------------
    DisTorch2 CLIP Model Layer Distribution
--------------------------------------------------
Layer Type         Layers   Memory (MB)   % Total
--------------------------------------------------
Embedding               1       1039.50     13.1%
Linear                358       6866.82     86.8%
RMSNorm               122          0.55      0.0%
Conv3d                  1          2.87      0.0%
--------------------------------------------------
[MultiGPU_DisTorch2_CLIP] Preserving 2 head layer(s) (1042.37 MB) on compute device: cuda:0
DisTorch2 CLIP Model Final Device/Layer Assignments
--------------------------------------------------
Device             Layers   Memory (MB)   % Total
--------------------------------------------------
cuda:0                395       4848.94     61.3%
cpu                    87       3060.80     38.7%
--------------------------------------------------
[MultiGPU_DisTorch2] DisTorch loading completed. Total memory: 7909.74MB
[MultiGPU_DisTorch2] Using CLIP-specific allocation for model 9b313bd7 (HEAD PRESERVATION ENABLED)
[MultiGPU_DisTorch2_CLIP] CLIP Compute Device: cuda:0
[MultiGPU_DisTorch2_CLIP] Expert String Examples:
  Direct(byte) Mode - cuda:0,500mb;cuda:1,3.0g;cpu,5gb* -> '*' cpu = over/underflow device, put 0.50gb on cuda0, 3.00gb on cuda1, and 5.00gb (or the rest) on cpu
  Ratio(%) Mode - cuda:0,8%;cuda:1,8%;cpu,4% -> 8:8:4 ratio, put 40% on cuda0, 40% on cuda1, and 20% on cpu
===============================================
    DisTorch2 Model Virtual VRAM Analysis
===============================================
Object   Role   Original(GB) Total(GB)  Virt(GB)
-----------------------------------------------
cuda:0   recip      23.55GB   26.55GB   +3.00GB
cpu      donor     124.97GB  121.97GB   -3.00GB
-----------------------------------------------
model    model       7.72GB    4.72GB   -3.00GB
[MultiGPU_DisTorch2_CLIP] Final CLIP Allocation String: cuda:0,0.2006;cpu,0.0240;cuda:1,0.0;cuda:2,0.0
==================================================
    DisTorch2 CLIP Model Device Allocations
==================================================
Device    VRAM GB    Dev %   Model GB    Dist %
--------------------------------------------------
cuda:0      23.55    20.1%       4.72     61.2%
cuda:1      23.56     0.0%       0.00      0.0%
cuda:2       5.61     0.0%       0.00      0.0%
cpu        124.97     2.4%       3.00     38.8%
--------------------------------------------------
    DisTorch2 CLIP Model Layer Distribution
--------------------------------------------------
Layer Type         Layers   Memory (MB)   % Total
--------------------------------------------------
Embedding               1       1039.50     13.1%
Linear                358       6866.82     86.8%
RMSNorm               122          0.55      0.0%
Conv3d                  1          2.87      0.0%
--------------------------------------------------
[MultiGPU_DisTorch2_CLIP] Preserving 2 head layer(s) (1042.37 MB) on compute device: cuda:0
DisTorch2 CLIP Model Final Device/Layer Assignments
--------------------------------------------------
Device             Layers   Memory (MB)   % Total
--------------------------------------------------
cuda:0                395       4848.94     61.3%
cpu                    87       3060.80     38.7%
--------------------------------------------------
[MultiGPU_DisTorch2] DisTorch loading completed. Total memory: 7909.74MB
loaded completely 21994.96320223999 19483.948791503906 True
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:28<00:00,  3.54s/it]
```

Given that you are not even making it to the allocation stage where this would be printed makes no sense.


(As a general note, please remove other custom_nodes from your workflows before submitting them or an issue based off of them. I cannot control the permutations that multiple additional custom_nodes can add to creating errors like this.)

**Comment by sinand99** [comment]
@pollockjj Hi again. 

1. I tried your workflow and I still get OOM. Actually workflow is irrelevant because the first thing running is your node and it just crashes in 2 seconds. Did you try it with 8GB card?

2. I have Crystools. VRAM before running the prompt:  0.6 GB and AFTER: 7.6 and it goes down to 0.6 again after OOM.

3. You can view the full log from "got prompt" to the end below.

```
got prompt
[MultiGPU Initialization] current_device set to: cuda:0
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load WanVAE
0 models unloaded.
loaded partially 128.0 127.9998779296875 0
[MultiGPU Initialization] current_text_encoder_device and current_text_encoder_initial_device set to: cuda:0
[MultiGPU_DisTorch2] Successfully patched ModelPatcher.partially_load
Using scaled fp8: fp8 matrix mult: False, scale input: False
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "G:\AI\Image\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\AI\Image\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "G:\AI\Image\ComfyUI\custom_nodes\comfyui-multigpu\distorch_2.py", line 941, in override
    temp_out = fn(*args, **kwargs)
  File "G:\AI\Image\ComfyUI\nodes.py", line 952, in load_clip
    clip = comfy.sd.load_clip(ckpt_paths=[clip_path], embedding_directory=folder_paths.get_folder_paths("embeddings"), clip_type=clip_type, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 845, in load_clip
    return load_text_encoder_state_dicts(clip_data, embedding_directory=embedding_directory, clip_type=clip_type, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 1062, in load_text_encoder_state_dicts
    clip = CLIP(clip_target, embedding_directory=embedding_directory, parameters=parameters, tokenizer_data=tokenizer_data, model_options=model_options)
  File "G:\AI\Image\ComfyUI\comfy\sd.py", line 113, in __init__
    self.cond_stage_model = clip(**(params))
                            ~~~~^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 84, in __init__
    super().__init__(device=device, dtype=dtype, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 48, in __init__
    super().__init__(device=device, dtype=dtype, name="qwen25_7b", clip_model=Qwen25_7BVLIModel, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\sd1_clip.py", line 675, in __init__
    setattr(self, self.clip, clip_model(device=device, dtype=dtype, model_options=model_options, **kwargs))
                             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_image.py", line 43, in __init__
    super().__init__(device=device, layer=layer, layer_idx=layer_idx, textmodel_json_config={}, dtype=dtype, special_tokens={"pad": 151643}, layer_norm_hidden_state=False, model_class=comfy.text_encoders.llama.Qwen25_7BVLI, enable_attention_masks=attention_mask, return_attention_masks=attention_mask, model_options=model_options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\sd1_clip.py", line 121, in __init__
    self.transformer = model_class(config, dtype, device, self.operations)
                       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\llama.py", line 392, in __init__
    self.visual = qwen_vl.Qwen2VLVisionTransformer(hidden_size=1280, output_hidden_size=config.hidden_size, device=device, dtype=dtype, ops=operations)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 300, in __init__
    VisionBlock(hidden_size, intermediate_size, num_heads, device, dtype, ops)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 241, in __init__
    self.mlp = VisionMLP(hidden_size, intermediate_size, device=device, dtype=dtype, ops=ops)
               ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\text_encoders\qwen_vl.py", line 228, in __init__
    self.down_proj = ops.Linear(intermediate_size, hidden_size, bias=True, device=device, dtype=dtype)
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\comfy\ops.py", line 385, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "G:\AI\Image\ComfyUI\venv\Lib\site-packages\torch\nn\modules\linear.py", line 106, in __init__
    torch.empty((out_features, in_features), **factory_kwargs)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 2.03 seconds
```

**Comment by pollockjj** [comment]
Reopening. Would like to get @sinand99 or other user's feedback before closing.

**Comment by sinand99** [comment]
@pollockjj Good news! Initial tests with Qwen image and Qwen edit are successful. Now it works properly 👍I will keep testing and if I get any bugs, I will inform you. 
Thanks for your effort. I really appreciate it.
