### ISSUE TITLE
Could not find module 'libcudart.so'

### ISSUE THREAD

**Issue by sszlot** [pollockjj/ComfyUI-MultiGPU#187]
Could not find module 'libcudart.so' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by sszlot** [comment]
Fixed by replacing the following function in p2p_registry.py:

def _get_libcudart():
    """Load libcudart.so once and cache the handle."""
    global _libcudart
    if _libcudart is None:
        _libcudart = ctypes.CDLL("libcudart.so")
    return _libcudart

by 

def _get_libcudart():
    global _libcudart
    if _libcudart is None:
        try:
            _libcudart = ctypes.CDLL("libcudart.so")  # Linux
        except OSError:
            _libcudart = ctypes.CDLL("cudart64_13.dll")  # Windows (Specific to CUDA 13)
    return _libcudart

**Comment by sszlot** [comment]
Workflow: https://github.com/pollockjj/ComfyUI-MultiGPU/blob/main/example_workflows/qwen_image_edit_2509%20unet%20clip%20distorch2.json

**Comment by woogerboy21** [comment]
hmm... i have also ran into this problem though not necessarily in windows.  when running the new comfy desktop the comfyui venv is created without users involvment and the library file isnt copied into the LD_LIBRARY_PATH that is mounted virtually read only during execution.  This in turn prevents this node from working properly since it cannot find the files neccessary from the cuda runtime (even though they get installed into the path of the comfyui  installation directory).  anyone else happen to know how to update the comfyui desktop virtual environment mounted path by chance?

runtime-install-path
/home/user/ComfyUI-Installs/ComfyUI/ComfyUI/.venv/lib/python3.13/site-packages/nvidia/cu13/lib/libcudart.so.13

venv-ld_library_path
rw-r--r-- 1 root root  51K Jun 17  2019 libappindicator.so.1
-rw-r--r-- 1 root root 188K Jun 17  2019 libgconf-2.so.4
-rw-r--r-- 1 root root  60K Jun 17  2019 libindicator.so.7
-rw-r--r-- 1 root root  31K Jun 17  2019 libnotify.so.4
-rw-r--r-- 1 root root  15K Jun 17  2019 libXss.so.1
-rw-r--r-- 1 root root  23K Jun 17  2019 libXtst.so.6
(.venv) user@machine /tmp/.mount_comfyuRLASx4/usr/lib$
