### ISSUE TITLE
Issues with ltxv13b

### ISSUE THREAD

**Issue by wsbagnsv1** [pollockjj/ComfyUI-MultiGPU#60]
Hey Its me again (; 
There seems to be an issue with the ltxv 13b model and distorch. Its not really that distorch doesnt work, it does but its rather weird to get it working. The log is below. It first tries to load the full model to vram, then distorch pops up and does its magic, but the original model stays in vram leading to an oom if the circumstances are allowing that. If you cancel sampling though vram clears up and afterwards distorch is clearly working. 
Would you mind helping me to figure out where the issue is? 

Requested to load LTXV
loaded completely 9223.76 8595.42236328125 True
===============================================
          DisTorch Virtual VRAM Analysis
===============================================
Object   Role   Original(GB) Total(GB)  Virt(GB)
-----------------------------------------------
cuda:0   recip      11.99GB   25.99GB  +14.00GB
cpu      donor      31.83GB   17.83GB  -14.00GB
-----------------------------------------------
model    model       8.21GB    0.00GB  -14.00GB

Allocation String  cuda:0,0.0000;cpu,0.4399
===============================================
          DisTorch Device Allocations
===============================================
Device         Alloc %    Total (GB) Alloc (GB)
-----------------------------------------------
cuda:0              0%         11.99      0.00
cpu                43%         31.83     14.00
-----------------------------------------------
     DisTorch GGML Layer Distribution
-----------------------------------------------
Layer Type      Layers   Memory (MB)   % Total
-----------------------------------------------
Linear             487       8401.92    100.0%
RMSNorm            192          1.50      0.0%
LayerNorm            1          0.00      0.0%
-----------------------------------------------
    DisTorch Final Device/Layer Assignments
-----------------------------------------------
Device          Layers   Memory (MB)   % Total
-----------------------------------------------
cuda:0               0          0.00      0.0%
cpu                680       8403.42    100.0%
-----------------------------------------------

**Comment by wsbagnsv1** [comment]
Also there is a workaround, if you load the model with a low res / frame count  then cancel sampling change settings and then do it again distorch works perfectly for some reason?

**Comment by wsbagnsv1** [comment]
Nvm I might have found the issue, somehow Reroute from utils caused that behaviour? very very weird, but distorch seems to work as expected again. So this shouldnt be a multigpu issue

**Comment by wsbagnsv1** [comment]
Bruh thought i found the issue, turns out it just tarted working for a second, then it stopped again /:

**Comment by wsbagnsv1** [comment]
it still will prevent ooms due to 

Warning: Model size is greater than 90% of recipient VRAM. 2.25 GB of GGML Layers Offloaded Automatically to Virtual VRAM.

But this only works the first time, if I then start to generate again I run into a oom, after that it works again

**Comment by pollockjj** [comment]
@wsbagnsv1 - The most recent version of ComfyUI-MultiGPU patches the memory management a bit earlier in the pipeline. If you are still using it and experiencing issues, please upgrade to 2.0.0 and use the DisTorch2 nodes. 

I believe your problem will be fixed. If you are still experiencing issues, feel free to re-open this issue or open a new one and we can start looking at your specific use case and what is giving you headaches.

Cheers!
